services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-dockerized-starter.onrender.com
      - key: APP_KEY
        sync: false
      - key: CACHE_DRIVER
        value: file
      - key: DB_CONNECTION
        value: mysql
      - key: DB_DATABASE
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USERNAME
        sync: false
      - key: REDIS_HOST
        value: redis-cache
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_HOST
        value: mailhog
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_PORT
        value: 1025
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file

  - type: redis
    name: redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all (not recommended for production)
