services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: docker build -t laravel-app .
    startCommand: docker run -p $PORT:80 laravel-app
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_starter
      - key: DB_USERNAME
        value: root
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailhog
      - key: MAIL_PORT
        value: 1025
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis

  - type: pserv
    name: mysql-database
    env: docker
    plan: free
    image: mysql:8.0
    envVars:
      - key: MYSQL_DATABASE
        value: laravel_starter
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_USER
        value: root

  - type: redis
    name: redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
